myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('myblog/', include('features.urls')),
                  path('myblog/', include('user.urls')),
                  path('myblog/', include('contact.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('login/', login_account, name='login'),
    path('logout/', logout_account, name='logout'),
    path('signup/', signup, name='signup'),
    path('change-profile/', ChangeProfilePhoto.as_view(), name="change-profile"),
    path('change-password/', set_new_password, name="change-password"),
    path('forgot-password/', ForgetPassword.as_view(), name="forgot-password"),
    path('profile/<str:username>/', ShowUserProfile.as_view(), name="show-profile"),
]

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ExtendUser
from django.core.exceptions import ValidationError


class LoginForm(forms.Form):
    username = forms.CharField(max_length=255, min_length=5)
    password = forms.CharField(widget=forms.PasswordInput)


GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )


class SignUpForm(UserCreationForm):
    gender = forms.ChoiceField(
        required=True,
        choices=GENDER_CHOICES,
    )
    image = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = ('username', 'image', 'gender', 'password1', 'password2', 'email')


class UpdateProfilePhotoForm(forms.ModelForm):
    class Meta:
        model = ExtendUser
        fields = ['image']


class SetNewPasswordForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 != password2:
            raise ValidationError(
                "password1 and password2 are not equal")


class ForgetPasswordForm(forms.Form):
    email = forms.EmailField()

templates/add-category.html
{% extends "base.html" %}
{% block title %}Add category{% endblock %}

{% block content %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
<form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
        {{ form}}

        <input type="submit" class="btn btn-success" value="OK">
    </div>
</form>

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}title{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'base-css.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"
          integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">


    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">


    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>


</head>
<body>


<div class="wrapper">
    <!-- Sidebar Holder -->
    <nav id="sidebar">
        <div class="sidebar-header">
            {% if user.is_authenticated %}
            <h3>{{user.username}}</h3>
            {% else %}
            <h3>BLOG </h3>
            {% endif %}
            </h3>
        </div>

        <ul class="list-unstyled components">
            <p>Pages</p>
            <li class="active">
                <a href="{% url 'home' %}">Home</a>

            </li>
            <li class="active">
                <a href="{% url 'category' %}">Category</a>
            <li class="active">
                <a href="{% url 'tags' %}">Tags</a>

                {% if user.is_authenticated %}
                <p>Pages</p>
            </li>
            <li class="active">
                <a href="{% url 'my-posts' %}">My posts</a>
            </li>
            <li class="active">
                <a href="{% url 'create-post' %}">Post a new photo</a>
            </li>
            <li class="active">
                <a href="{% url 'change-profile' %}">Change profile photo</a>
            </li>
            <li class="active">
                <a href="{% url 'change-password' %}">Change password</a>
            </li>
            {% endif %}

        </ul>
        <ul class="list-unstyled components">
            <li>
        <a href="{% url 'get-message' %}">Contact us</a>
            </li>
            </ul>


    </nav>

    <!-- Page Content Holder -->
    <div id="content">

        <nav class="navbar navbar-default">
            <div class="container-fluid">

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            {% if user.is_authenticated %}
                            <a class="d-flex align-items-center " href="/myblog/profile/{{user.username}}/"
                               role="button">
                                {% if user.extenduser.image %}
                                <img src="{{user.extenduser.image.url}}" class="rounded-circle"
                                     height="25" alt="" loading="lazy">
                                {% elif user.extenduser.gender == 'M' %}
                                <img src="{% static 'male-avatar.jpg' %}" class="rounded-circle"
                                     height="25" alt="" loading="lazy">
                                {% else %}
                                <img src="{% static 'female-avatar.jpg' %}" class="rounded-circle"
                                     height="25" alt="" loading="lazy">
                                {% endif %}

                            </a>


                            {% else %}
                            <a href="{% url 'login' %}">Login</a>
                            {% endif %}
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            {% if user.is_authenticated %}
                            <a href="{% url 'logout' %}">logout</a>
                            {% else %}
                            <a href="{% url 'signup' %}">SignUp</a>
                            {% endif %}
                        </li>

                    </ul>

                    <form class="form-inline mt-3 navbar-right justify-content-center" action="{% url 'search' %}"
                          method="GET">
                        <input class="form-control " type="search" placeholder="Search" aria-label="Search" name="q">
                        <button class="btn btn-outline-success " type="submit">Search</button>
                    </form>

                    <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn ">
                        <i class="glyphicon glyphicon-align-left"></i>
                    </button>
                </div>
            </div>
        </nav>


        <div class="container">

            {% block content %}


            {% endblock content %}

        </div>

    </div>
</div>


<!-- jQuery CDN -->
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<!-- Bootstrap Js CDN -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<!-- jQuery Custom Scroller CDN -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {


        $('#sidebarCollapse').on('click', function () {
            $('#sidebar, #content').toggleClass('active');
            $('.collapse.in').toggleClass('in');
            $('a[aria-expanded=true]').attr('aria-expanded', 'false');
        });
    });
</script>


</body>
</html>

templates/category.html
{% extends "base.html" %}
{% block title %}Category{% endblock %}


{% block content %}
{% load static %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col">Category title</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for category in categories %}
                <tr>
                    <td style="width: 85%">{{category.title}}</td>
                    <td>
                        <a type="button" class="btn btn-primary" href="/myblog/categories/{{category.title}}"><i class="far fa-eye"></i></a>
                        <a type="button" class="btn btn-success" href="/myblog/categories/edit/{{category.title}}"><i class="fas fa-edit"></i></a>
                        <a type="button" class="btn btn-danger" href="/myblog/categories/delete/{{category.title}}"><i class="far fa-trash-alt"></i></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<a type="button" class="btn btn-primary" href="{% url 'add-category' %}" style="width: 100%">Add a new category</a>
{% endblock content %}

templates/create-post.html
{% extends "base.html" %}
{% block title %}Post your photo{% endblock %}


{% block content %}
{% load static %}


<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<link rel="stylesheet" href="{% static 'create-post-css.css' %}">
<script src="{% static 'create-post-js.js' %}"></script>
<style>
    input, textarea, select{
    width:100%;
}
    label{
        display: block;
        width : 100px:
    }
</style>
<div class="row justify-content-center ">
    <div class="col-md-6">
        <article class="card">
            <header class="card-header">
                <h4 class="card-title text-center mt-2">Post your photo</h4>
            </header>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">

                    <div class="input-group image-preview">
                        <input type="text" class="form-control image-preview-filename" disabled="disabled">
                        <span class="input-group-btn">
                    <button type="button" class="btn btn-default image-preview-clear" style="display:none;">
                        <span class="glyphicon glyphicon-remove"></span> Clear
                    </button>
                    <div class="btn btn-default image-preview-input">
                        <span class="glyphicon glyphicon-folder-open"></span>
                        <span for="id_image" class="image-preview-input-title">Browse</span>
                        <input type="file" accept="image/png, image/jpeg, image/gif" id="id_image" name="image"/>
                    </div>
                </span>
                    </div>

                    <br>
                    <div class="form-group">
                        {{ form.title.errors }}
                        <label for="{{ form.title.id_for_label }}">Title</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        {{ form.caption.errors }}
                        <label for="{{ form.caption.id_for_label }}">Caption</label>
                        {{ form.caption }}
                    </div>
                    <div class="fieldWrapper">
                        {{ form.category.errors }}
                        <label for="{{ form.category.id_for_label }}">Category</label>
                        {{ form.category }}
                    </div>
                    <div class="fieldWrapper">
                        {{ form.tags.errors }}
                        <label for="{{ form.tags.id_for_label }}">Tag</label>
                        {{ form.tags }}
                    </div>
                    {% if form.status %}
                    <div class="fieldWrapper">
                        {{ form.status.errors }}
                        <label for="{{ form.status.id_for_label }}">Status</label>
                        {{ form.status }}
                    </div>
                    {% endif %}

                    <button type="submit" class="btn btn-primary btn-block">Post</button>
            </div>
            </form>
        </article>
    </div>
</div>
</div>


{% endblock content %}

templates/delete-post.html
{% extends "base.html" %}
{% block title %}Delete post{% endblock %}


{% block content %}
{% load static %}

<div class="container">
    <div class="col-md-12 my-3">
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}
            <div class="text-center">
                <strong>Are you sure you want to delete {{post.title}} ?</strong>
                <br>
                <input class="btn btn-danger" type="submit" value="YES">
                <a href="{%url 'my-posts' %}" class="btn btn-primary">NO</a>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

templates/edit-tag.html
{% extends "base.html" %}
{% block title %}Edit {{tag.name}}{% endblock %}
{% block content %}
<div class="container">
    <div class="col-md-12 my-3">
        <form action="" method="post">
            {% csrf_token %}
            <div class="text-center">
                {{ form}}

                <input type="submit" class="btn btn-success" value="OK">
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/forget-password.html
{% extends "base.html" %}
{% block title %}Forget password{% endblock %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form action="" method="post">
    {% csrf_token %}
    <div class="text-center">
        {{ form}}
        <input type="submit" class="btn btn-success" value="send">
    </div>
</form>

{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}


{% block content %}
{% load static %}

{% for post in posts %}
{% if post.status == 'published' %}
<div class="card my-5 p-5" style="width: 100%; border-color: blue">
    <div class="card-block">
        <h1 class="card-title">{{post.title}}</h1>
        <a href="/myblog/profile/{{post.publisher.user.username}}/" class="card-subtitle text-muted">{{post.publisher.user.username}}</a>
    </div>
    <img data-src="holder.js/100px180/?text=Image" alt="Image [100%x180]"
         src="{{post.image.url}}"
         data-holder-rendered="true" style=" display: block;">
    <div class="card-block">
        {% if post.caption %}
        <hr>
        <div class="text-center">{{post.caption}}</div>
        <hr>
        {% endif %}

        {% if post.tags %}
        {% for tag in post.tags.all %}
        <p style="color: blue">#{{tag.name}}</p>
        {% endfor %}
        <hr>
        {% endif %}


        <small class="card-text">{{post.created_at}}</small>
        <a href="/myblog/post-detail/{{post.slug}}/" class="card-link" style="float: right">comments</a>
    </div>
</div>
{% endif %}
{% endfor %}
<div class="pagination "style="float: right">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

templates/login-form.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}


{% block content %}
{% load static %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card border-0 shadow rounded-3 my-5">
            <div class="card-body p-4 p-sm-5">
                <h5 class="card-title text-center mb-5 fw-light fs-5">Sign In</h5>

                {% if request.GET.next %}

                <form action="{% url 'login' %}?next={{request.GET.next}}" method="post">

                    {% else %}
                    <form action="{% url 'login' %}" method="post">
                        {% endif %}


                        {% csrf_token %}

                        {% if message %}
                        <strong style="color: red">
                            <ul class="errorlist">
                                <li>{{message}}</li>
                            </ul>
                        </strong>

                        {% endif %}

                        <div class="form-floating mb-3">

                            <input type="text" class="form-control" id="id_username" name="username">
                            <label for="id_username">Username</label>
                        </div>
                        <div class="form-floating mb-3">
                            <input type="password" class="form-control" id="id_password" name="password">
                            <label for="id_password">Password</label>
                        </div>
                        <a href="{% url 'forgot-password' %}">Forget password?</a>
                        <div class="d-grid">
                            <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit"
                                    style="width: 100%">Sign
                                in
                            </button>
                        </div>
                    </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/new-password.html
{% extends "base.html" %}
{% block title %}Change password{% endblock %}


{% block content %}
{% load static %}
<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <header class="card-header">
                <h4 class="card-title text-center mt-2">Change password</h4>
            </header>
            <article class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        <label for="id_password">Password</label>
                        <input class="form-control" type="password" id="id_password" name="password" required>
                        <strong style="color: red">{{ form.password.errors }}</strong>
                    </div>

                    <div class="form-group">
                        <label for="id_password1">New password</label>
                        <input class="form-control" type="password" id="id_password1" name="password1" required>
                        <strong style="color: red">{{ form.password1.errors }}</strong>
                    </div> <!-- form-group end.// -->
                    <div class="form-group">
                        <label for="id_password2">Repeat password</label>
                        <input class="form-control" type="password" id="id_password2" name="password2" required>
                        <strong style="color: red">{{ form.password2.errors }}</strong>
                    </div> <!-- form-group end.// -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> OK </button>
                    </div>

                </form>
            </article>

        </div>
    </div>

</div>
{% endblock content %}

templates/signup.html
{% extends "base.html" %}
{% block title %}SignUp{% endblock %}


{% block content %}
{% load static %}


<div class="row justify-content-center">
    <div class="col-md-6">
        <div class="card">
            <header class="card-header">
                <h4 class="card-title text-center mt-2">Sign up</h4>
            </header>
            <article class="card-body">


                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.non_field_errors }}

                    <div class="form-group">

                        <label for="id_username">Username</label>
                        <input type="text" class="form-control" placeholder="" id="id_username" name="username"
                               required>
                        <strong style="color: red">{{ form.username.errors }}</strong>

                    </div> <!-- form-group end.// -->
                    <div class="form-group">

                        <label for="id_email">Email</label>
                        <input type="email" class="form-control" placeholder="" id="id_email" name="email">

                        {% if e_message %}
                        <strong style="color: red">{{ e_message }}</strong>
                        {% endif %}

                    </div>
                    <div class="form-group">
                        <label class="form-check form-check-inline" for="id_gender">
                            <input class="form-check-input" type="radio" name="gender" id="id_gender" value="M"
                                   required>
                            <span class="form-check-label"> Male </span>
                        </label>
                        <label class="form-check form-check-inline" for="id_gender">
                            <input class="form-check-input" type="radio" name="gender" id="id_gender" value="F"
                                   required>
                            <span class="form-check-label"> Female</span>
                        </label>
                    </div> <!-- form-group end.// -->

                    <div class="form-group">
                        <label for="id_image">Profile picture</label>
                        <input id="id_image" type="file" class="" name="image">
                    </div>

                    <div class="form-group">
                        <label for="id_password1">Password</label>
                        <input class="form-control" type="password" id="id_password1" name="password1" required>
                        <strong style="color: red">{{ form.password1.errors }}</strong>
                    </div> <!-- form-group end.// -->
                    <div class="form-group">
                        <label for="id_password2">Repeat password</label>
                        <input class="form-control" type="password" id="id_password2" name="password2" required>
                        <strong style="color: red">{{ form.password2.errors }}</strong>
                    </div> <!-- form-group end.// -->
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary btn-block"> Register</button>
                    </div> <!-- form-group// -->
                    <small class="text-muted">By clicking the 'Sign Up' button, you confirm that you accept our <br>
                        Terms of use and Privacy Policy.</small>
                </form>
            </article> <!-- card-body end .// -->
            <div class="border-top card-body text-center">Have an account? <a href="/myblog/login">Log In</a></div>
        </div> <!-- card.// -->
    </div> <!-- col.//-->

</div>
{% endblock content %}

templates/tag-detail.html
{% extends "base.html" %}
{% block title %}{{tag.name}}{% endblock %}


{% block content %}
{% load static %}

{% for post in posts %}

{% if post.status == 'published' %}
<div class="card my-5 p-5" style="width: 100%; border-color: blue">
    <div class="card-block">
        <h1 class="card-title" >{{post.title}}</h1>
        <a href="/myblog/profile/{{post.publisher.user.username}}/" class="card-subtitle text-muted">{{post.publisher.user.username}}</a>
    </div>
    <img data-src="holder.js/100px180/?text=Image" alt="Image [100%x180]"
         src="{{post.image.url}}"
         data-holder-rendered="true" style=" display: block;">
    <div class="card-block">
        {% if post.caption %}
        <hr>
        <div class="text-center">{{post.caption}}</div>
        <hr>
        {% endif %}
        {% if post.tags %}
        {% for tag in post.tags.all %}
        <p style="color: blue">#{{tag.name}}</p>
        {% endfor %}
        <hr>
        {% endif %}
        <small class="card-text">{{post.created_at}}</small>
        <a href="/myblog/post-detail/{{post.slug}}/" class="card-link" style="float: right">comments</a>
    </div>
</div>
{% endif %}

{% endfor %}



{% endblock content %}

templates/tags.html
{% extends "base.html" %}
{% block title %}Tags{% endblock %}


{% block content %}
{% load static %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th scope="col"><small>number of posts contain this tag</small></th>
                    <th scope="col">Tag name</th>
                    <th scope="col">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for tag in tags %}


                <tr>
                    <td style="width: 10%">{{tag.posts}}</td>
                    <td style="width: 75%">{{tag.name}}</td>
                    <td>
                        <a type="button" class="btn btn-primary" href="/myblog/tags/{{tag.name}}"><i
                                class="far fa-eye"></i></a>
                        <a type="button" class="btn btn-success" href="/myblog/tags/edit/{{tag.name}}"><i
                                class="fas fa-edit"></i></a>
                        <a type="button" class="btn btn-danger" href="/myblog/tags/delete/{{tag.name}}"><i
                                class="far fa-trash-alt"></i></a>
                    </td>
                </tr>


                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<a type="button" class="btn btn-primary" href="{% url 'add-tag' %}" style="width: 100%">Add a new tag</a>
{% endblock content %}

templates/thanks-for-submission.html
{% extends "base.html" %}
{% block title %}Thanks!{% endblock %}

{% block content %}
{% load static %}

<div class="jumbotron text-center">
    <h1 class="display-3">Thank You!</h1>
    <p class="lead"><strong>Your submission has been received.</strong></p>
    <p class="lead">
    <a class="btn btn-primary btn-sm" href="/myblog/home" role="button">Continue to homepage</a>
  </p>
</div>
{% endblock content %}